### ISSUE TITLE
Reorganizing logger directory

### ISSUE THREAD

**Issue by MartinIngesen** [foospidy/HoneyPy#16]
Reorganizing logger directory
 
I would like to start the discussion around reorganizing the /lib/ directory to be more like the plugins directory.

- /
    - /lib/
        - \_\_init\_\_.py
        - honeypy\_console.py
        - honeypy\_twitter.py
        - ...
    - /plugins/
        - \_\_init\_\_.py
        - /Echo/
            - Echo.py
        - /Random/
            - Random.py
        - ...

I suggest using the same directory structure as /plugins/, eg:

- /
    - /loggers/
        - \_\_init\_\_.py
        - /console/
            - honeypy\_console.py
        - /twitter/
            - honeypy\_twitter.py
        - ...
    - /plugins/
        - \_\_init\_\_.py
        - /Echo/
            - Echo.py
        - /Random/
            - Random.py
        - ...

Pros:
- More descriptive folder name/structure
- Ability to organize files by loggers
- Ability to add README and other documentation to the loggers, without cluttering the /lib/ folder.

Cons:
- More folders

I can make this into a pull request if this is of interest. Please comment and give feedback on this.

**Comment by foospidy** [comment]
This is great, I think we should do it. One question, honeypy_console.py, honeypy_log_triage.py, and followtail.py are not "loggers", do you think they should remain in the lib directory?
