### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by infolookup** [foospidy/HoneyPy#28]
I attempted to install via downloading version 0.5.2 and running it I also tried using the HoneyPyPi script and in both cases I am getting the same issues when running the following the initial setup:

```
./ipt_set_tcp 7 10007
./ipt_set_udp 7 10007
./ipt_set_tcp 8 10008
./ipt_set_udp 8 10008
Traceback (most recent call last):
  File "Honey.py", line 113, in <module>
    plugin                   = importlib.import_module(plugin_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/HoneyPy-0.5.2/plugins/TelnetUnix/__init__.py", line 5, in <module>
    from TelnetUnix import pluginFactory
  File "/opt/HoneyPy-0.5.2/plugins/TelnetUnix/TelnetUnix.py", line 11, in <module>
    from clilib import *
ImportError: No module named clilib
```

**Comment by foospidy** [comment]
Sorry for this. It looks like you may not have clilib installed. Instructions here https://github.com/foospidy/clilib

I'll look into making that module easier to obtain (or bundle it in).

Alternatively, you can disable the TelnetUnix plugin via config - if you weren't planning to use that plugin.

I was planning to push new updates this week, so I'll try to address this as well.

**Comment by foospidy** [comment]
https://github.com/foospidy/HoneyPy/pull/30

The pull request above will resolve the clilib dependency. You no longer need to install it seperately. Please let me know if you experience any other issues.
