### ISSUE TITLE
TelnetUnix plugin

### ISSUE THREAD

**Issue by alfonsocaponi** [foospidy/HoneyPy#3]
I've a issue starting TelnetUnix plugin.
My etc/services.cfg

[Telnet]
plugin      = TelnetDebian7
low_port    = tcp:23
port        = tcp:10009
description = Emulate Debian telnet login vai tcp.
enabled     = No

[TelnetUnix]
plugin      = TelnetUnix
low_port    = tcp:23
port        = tcp:10009
description = Emulate Unix telnet login vai tcp.
enabled     = Yes

 python Honey.py
Your service configuration suggests that you want to run on at least one low port!
To enable port redirection run the following ipt-kit (https://github.com/foospidy/ipt-kit) commands as root:

./ipt_set_tcp 7 10007
./ipt_set_udp 7 10007
./ipt_set_tcp 8 10008
./ipt_set_udp 8 10008
Traceback (most recent call last):
  File "Honey.py", line 78, in <module>
    plugin                   = importlib.import_module(plugin_module)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/root/HoneyPy/plugins/TelnetUnix/**init**.py", line 5, in <module>
    from TelnetUnix import pluginFactory
  File "/root/HoneyPy/plugins/TelnetUnix/TelnetUnix.py", line 11, in <module>
    from clilib import *
  File "/usr/local/lib/python2.7/dist-packages/clilib-0.0.0-py2.7.egg/clilib/**init**.py", line 14, in <module>
    from clilib import *
  File "/usr/local/lib/python2.7/dist-packages/clilib-0.0.0-py2.7.egg/clilib/clilib.py", line 10, in <module>
    from unix import *
ImportError: No module named unix

**Comment by foospidy** [comment]
Based on the install instructions you added to the readme (https://github.com/foospidy/HoneyPy/blob/master/plugins/TelnetUnix/readme.txt) - did that resolve this issue?

**Comment by alfonsocaponi** [comment]
No. It works if add "sys.path.append('/..path../clilib/clilib/unix/')" to Honey.py :)

**Comment by MartinIngesen** [comment]
Should this be closed, @foospidy?

**Comment by foospidy** [comment]
It actually can be closed now @MartinIngesen. I left it open for a while as I'd like to have a better way to install/include clilib. I recently noticed the install instructions in the readme were buggy, but that is now fixed. So I'm more confident about the install.
