### ISSUE TITLE
introduce "quickstart" in top-level README.md

### ISSUE THREAD

**Issue by noah04** [foospidy/HoneyPy#37]
What do you think about introducing a quickstart-section in the projects `README.md`? Something like:

``` shell
git clone [...]
cd [...]
pipenv install && pipenv run ./Honey.py
```
.. with some additional words of explanation?

**Comment by foospidy** [comment]
I think that makes sense. Also, it might not be a bad idea to add a quickstart page to the docs, and then link to that from the readme.md. But I'm ok with it either way.
