### ISSUE TITLE
Allow service profiles to be combined

### ISSUE THREAD

**Issue by mattjoyce** [foospidy/HoneyPy#41]
Just wondering how much interest there would be in being able to activate multiple service profiles.
This would enable combing base services with functional service, such as WindowsServer+MSSQL, Linux+Apache+MYSQL.

The approaches I have thought about are : 
1 - stop using services.cfg and list the active service profiles in honey.cfg
Honey.py can iterate through the described services 
this would allow for service profiles to be commented in/out pretty easy

```
[Services]
services.windows.profile
services.mssql.profile
//service.foo.profile
```

2 - stop using service.cfg and instead use a folder etc/active 
Honey.py can read any file in etc/active, this would allow for symlinks from etc/profile

**Comment by mattjoyce** [comment]
3. Allow service profiles to be nested using an Include primitive.

**Comment by foospidy** [comment]
I think this is a great idea. Would the expectation be the user manages the symlinks?

**Comment by mattjoyce** [comment]
Yes, users can create symlinks or copy the file.  That's how Apache confs work in Debian, or did (been a while).

We can make it backward compatible, by leaving service.cfg as is, and adding the config option ActiveServiceProfilePath='etc/active'.

**Comment by foospidy** [comment]
https://github.com/foospidy/HoneyPy/pull/52
