### ISSUE TITLE
Refactoring logtail idea

### ISSUE THREAD

**Issue by mattjoyce** [foospidy/HoneyPy#44]
honeypy_logtail current requires editing to incorporate new loggers.
An alternate approach would be to iterate through each section in honeypy.cfg, and pass the line and the relevant section options to a function residing in loggers.

This would keep all the loggers code in the loggers folder.
I'd be happy to work on this if it a useful change.

**Comment by foospidy** [comment]
I think it would be very useful. Sounds like it would be a good optimization of code, and help make developing new loggers easier. 👍

**Comment by mattjoyce** [comment]
Pull request submitted for this issue.

**Comment by foospidy** [comment]
https://github.com/foospidy/HoneyPy/pull/48
