### ISSUE TITLE
Why all data encoded with .encode('hex')?

### ISSUE THREAD

**Issue by slavaGanzin** [foospidy/HoneyPy#58]
Hello

1. I'm curious why all data is encoded in hex? 
2. [Would it be OK if I add decoding in file logger? ](https://github.com/slavaGanzin/HoneyPy/blob/master/loggers/file/honeypy_file.py#L60)

p.s. Can't find your email so I created issue here

**Comment by foospidy** [comment]
Thanks for the question, no problem asking here. 

The data is encoded to effectively neuter malicious payloads. This helps to avoid any possible code or command injection issues when storing the data or processing it upstream.  Also, if you want to log raw payloads, many will contain return characters so you'll end up with multiline entries in the log file. Perhaps that is ok for your use case.

If you want to add that feature, I recommend making that a configurable option so users can opt-in to using it. So default would be to encode, but a user can add something like `encode = False` in the config file.

make sense?

**Comment by slavaGanzin** [comment]
I see your point. 

> Also, if you want to log raw payloads, many will contain return characters so you'll end up with multiline entries in the log file. 

I'll add generic escaping to avoid this

> recommend making that a configurable option

Will do it this way

Thanks for your answers
